// Every picture on the site, for the /gallery collage.
export type Shot = { src: string; alt: string; tag: "Parties" | "Stations" | "Themes" };

export const ALL_SHOTS: Shot[] = [
  { src: "/media/hero-mixed.jpg", alt: "Kids showing off crowns, tees, slippers, squishies and sneakers", tag: "Parties" },
  { src: "/photos/real-spidey-boy.jpg", alt: "Spider-Man themed birthday at StyleChild HQ", tag: "Parties" },
  { src: "/photos/ai-crowns.jpg", alt: "Girls wearing crowns they decorated", tag: "Parties" },
  { src: "/photos/real-kids-sneakers.jpg", alt: "Kids decorating sneakers together at StyleChild HQ", tag: "Parties" },
  { src: "/themes/candyland.jpg", alt: "Candyland party candy bar and candy boxes", tag: "Themes" },
  { src: "/photos/real-cupcakes.jpg", alt: "DIY cupcake decorating trays", tag: "Stations" },
  { src: "/photos/hq-party.jpg", alt: "Birthday group at StyleChild HQ in Boca Raton", tag: "Parties" },
  { src: "/photos/ai-slippers.jpg", alt: "Personalized fur slippers with names and icons", tag: "Stations" },
  { src: "/photos/real-lipgloss-bar.jpg", alt: "Lip gloss keychain and charm bar", tag: "Stations" },
  { src: "/themes/princess.jpg", alt: "Princess + Prince wand and crown making", tag: "Themes" },
  { src: "/photos/ai-boys.jpg", alt: "Boys showing custom sneakers and custom tees", tag: "Parties" },
  { src: "/photos/strip-3.jpg", alt: "Kids customizing white sneakers at a party table", tag: "Parties" },
  { src: "/photos/real-birthday-girl.jpg", alt: "Birthday girl in front of the StyleChild graffiti wall", tag: "Parties" },
  { src: "/themes/caboodle.jpg", alt: "Caboodle Beauty Bash decorating", tag: "Themes" },
  { src: "/photos/outdoor-kicks.jpg", alt: "Custom Kicks Bar at an outdoor party", tag: "Stations" },
  { src: "/photos/real-wicked-table.jpg", alt: "Wicked themed sneaker party table", tag: "Parties" },
  { src: "/themes/superhero.jpg", alt: "Superhero Bash capes and masks", tag: "Themes" },
  { src: "/photos/ai-mixed.jpg", alt: "Kids holding squishies, candy boxes and a custom sweatshirt", tag: "Parties" },
  { src: "/photos/strip-2.jpg", alt: "Bead bar and party décor", tag: "Stations" },
  { src: "/themes/spa.jpg", alt: "Spa Craft Party brushes, clips and mini manis", tag: "Themes" },
  { src: "/photos/real-spidey-boxes.jpg", alt: "Personalized Spider-Man party boxes", tag: "Stations" },
  { src: "/photos/strip-4.jpg", alt: "Kids decorating t-shirts with stencils", tag: "Parties" },
  { src: "/themes/sports.jpg", alt: "All Star Sports custom balls and jerseys", tag: "Themes" },
  { src: "/photos/table-party.jpg", alt: "Party table with white sneakers and markers", tag: "Parties" },
  { src: "/photos/real-hq-booth.jpg", alt: "StyleChild heat-transfer booth at an event", tag: "Stations" },
  { src: "/themes/squishy.jpg", alt: "Make Your Own Squishy party", tag: "Themes" },
  { src: "/photos/bash-in-a-box.jpg", alt: "Bash in a Box kit with sneakers, laces and beads", tag: "Stations" },
  { src: "/photos/strip-1.jpg", alt: "Rainbow laces and markers", tag: "Stations" },
  { src: "/themes/sneaker.jpg", alt: "Sneaker Styler Bar", tag: "Themes" },
  { src: "/media/hero-poster.jpg", alt: "Kids customizing sneakers and tees at an outdoor party", tag: "Parties" },
  { src: "/photos/strip-5.jpg", alt: "Stencil doodles on a sneaker", tag: "Stations" },
];
